name: Heidegger for dummies
favicon: null
layout_spectrum: 0.47786
typography_spectrum: 0.5038
title: Heidegger for dummies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#061d2b'
    - '#8fd3be'
    - '#3e6644'
    - '#e0a15a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
